
services:
  postgres:
    image: postgres:latest
    container_name: graham_postgres
    environment:
      POSTGRES_USER: graham_user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: graham_analyzer
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/postgres/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graham_user "]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
